# Generated by Django 4.2.3 on 2023-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/{{ user}}/'),
            preserve_default=False,
        ),
    ]
